feat: setup map context
camptocamp/rennes3d-front pull request #6
Opened 2022-09-16 06:46 UTC by akhelouat

- Adding 2d 3d map context. [GSREN3D-149](https://jira.camptocamp.com/browse/GSREN3D-149)

![image](https://user-images.githubusercontent.com/58878221/190573621-f425b44f-c946-41c7-83d9-3453e5c08679.png)

2022-09-16 11:31 UTC, fgravin requested changes
Thanks for the PR.
Some minor comments and an important question about map-core-demo.

Also, the design of your component and your service is not well structured.
The map is not shared the proper way.

2022-09-16 11:31 UTC, fgravin commented on src/components/map/MapContext.vue
> +:deep(.mapElement) {
I will rework the global layout of the page, but this is not a good practice.
the map should take the full width/height and its container should set up the size

2022-09-16 11:31 UTC, fgravin commented on src/services/vcmap.ts
> +export default async function initMap(
I dont understand the divergences with https://github.com/virtualcitySYSTEMS/map-core-demo/blob/dbde70bdefa5e6ae252a8545ec9a7068e5ef8d50/src/api/api.js#L27

Could explain why you haven't just copied this file ?

2022-09-16 11:31 UTC, fgravin commented on src/services/vcmap.ts
> +  window.mapContext = context
really not the way the share objects.
also, if you create 2 maps, the first one reference will be lost.

2022-09-26 09:50 UTC, fgravin commented
@akhelouat you pushed the data, never do that on github it's not meant for that.
Also I can't review your second commit cause it's too large, please remove the `/data` folder and push again, Thanks

2022-09-26 12:01 UTC, akhelouat commented
@fgravin it's done

2022-09-26 19:46 UTC, fgravin reviewed
Thanks for the update.
Unfortunately, the code is too approximative

- lot of useless code
- lack of architecture
- lack of understanding

It was easier to propose something almost from scratch in https://github.com/camptocamp/rennes3d-front/pull/11
I used some of your code though, thanks

I am closing this one.

2022-09-26 19:46 UTC, fgravin commented on map.config.json
> +{
good idea to have a config, but it's way too complex though, you should have the minimal config to make it work and understand how the map is built.

2022-09-26 19:46 UTC, fgravin commented on src/components/map/MapContext.vue
> +  initMap(is3d.value, { x: -1.67, y: 48.1147, z: 16000, pitch: -10 }, 'map')
you should not init the map again and again while toggling 3D mode, the `mapCollection` is used for that with the `setActiveMap` method

2022-09-26 19:46 UTC, fgravin commented on src/services/vcmap.ts
> +      url: 'data/buildings',
should be http urls for now

2022-09-26 19:54 UTC, closed without merging

2022-09-27 22:26 UTC, akhelouat commented
@fgravin Thanks for the review I will try to improve